version: "3"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    pid: host
    network_mode: host
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - 9100:9100
    labels:
      org.label-schema.group: "monitoring"
