version: "3"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    pid: host
    network_mode: host
    volumes:
      - "/:/host:ro,rslave"
    labels:
      org.label-schema.group: "monitoring"
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    restart: unless-stopped
    network_mode: "host"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600 --cleanup
